In [1]:
import random
import numpy as np

In [3]:
s = [10,16,10]
s[1:]

[16, 10]

In [11]:
y=7
np.random.randn(y,1)
#randn: random a y-by-1 array in Gaussian distribution

array([[-1.72972955],
       [-1.00890278],
       [-0.0538442 ],
       [-2.38960948],
       [-0.2914559 ],
       [ 0.39243415],
       [ 1.38514141]])

In [20]:
zipped = zip(s[:-1],s[1:])
for i in zipped:
    print(i)

(10, 16)
(16, 10)


In [23]:
bias=[np.random.randn(y ,1) for y in s[1:]]

In [24]:
len(bias[0])

16

In [25]:
for i in xrange(4):
    print(i)

NameError: name 'xrange' is not defined

In [26]:
aaa=[[1,2,3],[1,2,3]]
aaa.shape

AttributeError: 'list' object has no attribute 'shape'

In [29]:
(i for i in range(10))

<generator object <genexpr> at 0x000002CBEE604D00>

In [31]:
a=np.array([[1,2,3]])
b = np.array([[3,4,5]])

In [32]:
a*b

array([[ 3,  8, 15]])

In [40]:
import pickle
import gzip

In [2]:
tt=np.random.rand(3,2)

In [3]:
tt

array([[0.79512644, 0.65869681],
       [0.20577943, 0.23823384],
       [0.65020759, 0.00614118]])

In [5]:
dd = np.random.randn(3,2)
dd

array([[ 0.3469359 , -0.96611445],
       [ 1.28834358, -1.44524584],
       [ 0.84862129,  0.74935495]])